server {
    listen 3000;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /_next/ {
        alias /usr/share/nginx/html/_next/;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }
}
